version: '3.8'
services:
  server:
    build: ./server
    container_name: api_server
    ports:
      - '3005:3005'
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    env_file: ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

